In [ ]:
import os
#Importing the necessary libraries
import pandas as pd
import numpy as np
import os
import glob
import tensorflow as tf

#Python Imaging Library
import PIL
from PIL import Image
import imageio

#For Data Viz
import matplotlib.pyplot as plt
import seaborn as sn
import numpy as np
import pathlib
import cv2
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import normalize
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.utils import to_categorical

In [ ]:
for dirname, _, filenames in os.walk('E:\\bACKUP\\mi\\PROJECTS 2018 IT\\BrainTumor\\Brain Tumor Prediction\\archive'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\annotations_all.json
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\annotations_test.json
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y701.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y702.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y703.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y704.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y705.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y706.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Prediction\archive\Br35H-Mask-RCNN\TEST\y707.jpg
E:\bACKUP\mi\PROJECTS 2018 IT\BrainTumor\Brain Tumor Predictio

In [ ]:
# Get the path of files
image_directory='E:\\bACKUP\\mi\\PROJECTS 2018 IT\\BrainTumor\\Brain Tumor Prediction\\archive\\'

no_tumor_images=os.listdir(image_directory+ 'no\\')
yes_tumor_images=os.listdir(image_directory+ 'yes\\')
# initialize dataset and label arrays
dataset=[]
label=[]
# set input size
INPUT_SIZE=64

In [ ]:
#loop over each image in each category
for i , image_name in enumerate(no_tumor_images):
    #read the image if its extension is .jpg
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread(image_directory+'no/'+image_name)
        image=Image.fromarray(image,'RGB')
        #resize the image
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        #append image arry in dataset list and its label in label list
        dataset.append(np.array(image))
        label.append(0)

        # same for yes images
for i , image_name in enumerate(yes_tumor_images):
    if(image_name.split('.')[1]=='jpg'):
        image=cv2.imread(image_directory+'yes/'+image_name)
        image=Image.fromarray(image, 'RGB')
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        dataset.append(np.array(image))
        label.append(1)


In [ ]:
dataset=np.array(dataset)
dataset

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        ...,

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0, 

In [ ]:
label=np.array(label)
label

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
print(len(label))

3000


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(dataset, label, test_size = 0.2, random_state = 42)

In [ ]:
print(x_train.shape)
print(y_train.shape)
print("#######################################")
print(x_test.shape)
print(y_test.shape)

(2400, 64, 64, 3)
(2400,)
#######################################
(600, 64, 64, 3)
(600,)


In [ ]:
# Normalise the data for training purpose
x_train = normalize( x_train, axis =1)
x_test = normalize( x_test, axis =1)

# Normalise the data for training purpose
#y_train = to_categorical(y_train, num_classes=2)
#y_test = to_categorical(y_test, num_classes=2)


In [ ]:
# Building a simple CNN model
model = Sequential()

model.add(Conv2D(32, (3,3), input_shape = (INPUT_SIZE, INPUT_SIZE, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32, (3,3), kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3,3),  kernel_initializer = 'he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
#model.add(Dense(2))
model.add(Activation('sigmoid'))
# model.add(Activation('softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 activation (Activation)     (None, 62, 62, 32)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 31, 31, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 activation_1 (Activation)   (None, 29, 29, 32)        0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 14, 14, 32)       0         
 2D)                                                    

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [ ]:
model.fit(x_train, y_train,
batch_size = 16,
verbose = 1, epochs = 10,
validation_data = (x_test, y_test),
shuffle = 'False')

Epoch 1/10
150/150 [==============================] - 33s 164ms/step - loss: 0.5522 - accuracy: 0.7150 - val_loss: 0.4476 - val_accuracy: 0.8083
Epoch 2/10
150/150 [==============================] - 24s 164ms/step - loss: 0.4089 - accuracy: 0.8208 - val_loss: 0.3328 - val_accuracy: 0.8700
Epoch 3/10
150/150 [==============================] - 24s 158ms/step - loss: 0.3175 - accuracy: 0.8725 - val_loss: 0.2376 - val_accuracy: 0.9050
Epoch 4/10
150/150 [==============================] - 23s 155ms/step - loss: 0.2455 - accuracy: 0.9067 - val_loss: 0.2082 - val_accuracy: 0.9150
Epoch 5/10
150/150 [==============================] - 23s 152ms/step - loss: 0.1683 - accuracy: 0.9438 - val_loss: 0.2017 - val_accuracy: 0.9267
Epoch 6/10
150/150 [==============================] - 22s 146ms/step - loss: 0.1180 - accuracy: 0.9588 - val_loss: 0.1190 - val_accuracy: 0.9667
Epoch 7/10
150/150 [==============================] - 27s 180ms/step - loss: 0.0800 - accuracy: 0.9725 - val_loss: 0.1078 - val_ac

In [ ]:
model.save('Brain_Tumor_detection.h5')

In [ ]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np

model = load_model('Brain_Tumor_detection.h5')
# Testing on one image
image = cv2.imread('E:\\bACKUP\\mi\\PROJECTS 2018 IT\\BrainTumor\\Brain Tumor Prediction\\archive\\pred\\pred13.jpg') #tumor detected
img = Image.fromarray(image)
img = img.resize((64,64))
img = np.array(img)
print(img)
input_img = np.expand_dims(img, axis=0)

result = model.predict(input_img)
print(result)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  1  1]
  [ 4  4  4]
  [ 4  4  4]
  ...
  [ 2  2  2]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [11 11 11]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 8  8  8]
  [22 22 22]
  [22 22 22]
  ...
  [10 10 10]
  [ 0  0  0]
  [ 0  0  0]]]
1/1 [==============================] - 1s 728ms/step
[[1.]]


In [ ]:
# Testing on one image
image = cv2.imread('E:\\bACKUP\\mi\\PROJECTS 2018 IT\\BrainTumor\\Brain Tumor Prediction\\archive\\pred\\pred0.jpg') # no tumor detected
img = Image.fromarray(image)
img = img.resize((64,64))
img = np.array(img)
print(img)
input_img = np.expand_dims(img, axis=0)

result = model.predict(input_img)
print(result)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
1/1 [==============================] - 0s 119ms/step
[[0.]]
